-- UX-workflows: productimport (Import Center), printprofielen en documentmetadata.
-- Puur additief: nieuwe tabellen en nullable kolommen; bestaande data en QR-URL's
-- blijven ongemoeid. Idempotent, zodat opnieuw draaien veilig is.

-- Importjobs. De geparste rijen staan tijdelijk in rows (jsonb-array van arrays,
-- in de volgorde van headers) en worden na afronden gewist; errors bewaart per rij
-- de fouten/waarschuwingen voor het foutrapport. Verwerking gaat in stukken (chunks)
-- van 250 rijen; current_chunk/processed_rows maken een onderbroken import hervatbaar
-- zonder rijen dubbel te verwerken.
CREATE TABLE IF NOT EXISTS dbo.productimports (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id integer NOT NULL REFERENCES dbo.companies(id),
  created_by integer NULL REFERENCES dbo.users(id),
  filename varchar(255) NOT NULL,
  file_type varchar(10) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'pending',
  headers jsonb NOT NULL DEFAULT '[]'::jsonb,
  column_mapping jsonb NULL,
  duplicate_strategy varchar(10) NULL,
  rows jsonb NULL,
  errors jsonb NOT NULL DEFAULT '[]'::jsonb,
  -- Rijnummers met een blokkerende fout (uit de validatie): die worden nooit verwerkt.
  error_rows integer[] NOT NULL DEFAULT '{}',
  validation_summary jsonb NULL,
  total_rows integer NOT NULL DEFAULT 0,
  processed_rows integer NOT NULL DEFAULT 0,
  current_chunk integer NOT NULL DEFAULT 0,
  success_count integer NOT NULL DEFAULT 0,
  created_count integer NOT NULL DEFAULT 0,
  updated_count integer NOT NULL DEFAULT 0,
  skipped_count integer NOT NULL DEFAULT 0,
  error_count integer NOT NULL DEFAULT 0,
  warning_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz NULL,
  completed_at timestamptz NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_productimports_status
    CHECK (status IN ('pending', 'validating', 'importing', 'completed', 'failed', 'cancelled')),
  CONSTRAINT chk_productimports_duplicate_strategy
    CHECK (duplicate_strategy IS NULL OR duplicate_strategy IN ('skip', 'update', 'create'))
);
CREATE INDEX IF NOT EXISTS ix_productimports_company_created ON dbo.productimports (company_id, created_at DESC);

-- Printprofielen per bedrijf. `settings` wordt in de API met Zod gevalideerd
-- (papier, labelindeling, printer, QR-instellingen, template).
CREATE TABLE IF NOT EXISTS dbo.printprofiles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id integer NOT NULL REFERENCES dbo.companies(id),
  name varchar(100) NOT NULL,
  description varchar(255) NULL,
  is_default boolean NOT NULL DEFAULT false,
  settings jsonb NOT NULL,
  created_by integer NULL REFERENCES dbo.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_printprofiles_company_id ON dbo.printprofiles (company_id);
-- Hooguit één standaardprofiel per bedrijf.
CREATE UNIQUE INDEX IF NOT EXISTS uq_printprofiles_company_default
  ON dbo.printprofiles (company_id) WHERE is_default;

-- Documentmetadata: geldigheid (certificaten/verklaringen), versie en uploader.
ALTER TABLE dbo.documents ADD COLUMN IF NOT EXISTS valid_until date NULL;
ALTER TABLE dbo.documents ADD COLUMN IF NOT EXISTS version varchar(30) NULL;
ALTER TABLE dbo.documents ADD COLUMN IF NOT EXISTS uploaded_by integer NULL REFERENCES dbo.users(id);
CREATE INDEX IF NOT EXISTS ix_documents_valid_until ON dbo.documents (valid_until) WHERE valid_until IS NOT NULL;

ALTER TABLE dbo.documents DROP CONSTRAINT IF EXISTS chk_documents_category;
ALTER TABLE dbo.documents ADD CONSTRAINT chk_documents_category
  CHECK (category IN ('document', 'manual', 'video', '3d_model', 'certificate', 'declaration'));

-- Snelle duplicaatdetectie bij import en zoeken op SKU/GTIN binnen een bedrijf.
CREATE INDEX IF NOT EXISTS ix_products_company_sku ON dbo.products (company_id, lower(sku)) WHERE sku IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_products_company_gtin ON dbo.products (company_id, gtin) WHERE gtin IS NOT NULL;
-- Scan-statistieken per product over een periode.
CREATE INDEX IF NOT EXISTS ix_scanevents_product_scanned_at ON dbo.scanevents (product_id, scanned_at);

-- Zelfde tweede slot als de rest van dbo: RLS aan, geen rechten voor publieke rollen.
ALTER TABLE dbo.productimports ENABLE ROW LEVEL SECURITY;
ALTER TABLE dbo.printprofiles ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON dbo.productimports FROM anon, authenticated;
    REVOKE ALL ON dbo.printprofiles FROM anon, authenticated;
  END IF;
END $$;
