-- Archief van productpaspoortversies (EN 18221:2026 §4.2, archivering).
--
-- Elke inhoudelijke wijziging van een gepubliceerd (of gearchiveerd, dus nog
-- publiek bereikbaar) paspoort levert een nieuwe, onveranderlijke versie op. Versie 1
-- is de stand bij de eerste publicatie; vanaf de eerste wijziging is er dus
-- historie. Integriteit en originaliteit:
-- - content_sha256: SHA-256 over de canonieke JSON van de snapshot;
-- - chain_sha256: SHA-256 over (vorige chain-hash | versienummer | content-hash |
--   tijdstip), zodat het weglaten, vervangen of herordenen van versies aantoonbaar is;
-- - de tabel is append-only: een trigger weigert elke UPDATE en DELETE.
--
-- Puur additief: bestaande tabellen en QR-URL's blijven ongemoeid. Idempotent.

CREATE TABLE IF NOT EXISTS dbo.passportversions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL REFERENCES dbo.products(id),
  company_id integer NOT NULL REFERENCES dbo.companies(id),
  public_id uuid NOT NULL,
  version_number integer NOT NULL,
  -- Canonieke inhoud van het paspoort op dat moment (incl. niet-openbare
  -- documentmetadata; de API filtert die per lezer, zie passport.service.js).
  snapshot jsonb NOT NULL,
  content_sha256 char(64) NOT NULL,
  previous_chain_sha256 char(64) NULL,
  chain_sha256 char(64) NOT NULL,
  -- Aanleiding: publish, update, archive, import, bulk, backfill, ...
  reason varchar(50) NOT NULL,
  created_by integer NULL REFERENCES dbo.users(id),
  created_at timestamptz NOT NULL,
  CONSTRAINT uq_passportversions_product_version UNIQUE (product_id, version_number),
  CONSTRAINT chk_passportversions_version_positive CHECK (version_number > 0)
);
CREATE INDEX IF NOT EXISTS ix_passportversions_public_id_created ON dbo.passportversions (public_id, created_at);
CREATE INDEX IF NOT EXISTS ix_passportversions_company_id ON dbo.passportversions (company_id);

CREATE OR REPLACE FUNCTION dbo.passportversions_append_only()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'dbo.passportversions is append-only (% geweigerd)', TG_OP
    USING ERRCODE = 'insufficient_privilege';
END;
$$;

DROP TRIGGER IF EXISTS trg_passportversions_append_only ON dbo.passportversions;
CREATE TRIGGER trg_passportversions_append_only
  BEFORE UPDATE OR DELETE ON dbo.passportversions
  FOR EACH ROW EXECUTE FUNCTION dbo.passportversions_append_only();

-- TRUNCATE omzeilt rij-triggers; daarom ook een statement-trigger.
DROP TRIGGER IF EXISTS trg_passportversions_no_truncate ON dbo.passportversions;
CREATE TRIGGER trg_passportversions_no_truncate
  BEFORE TRUNCATE ON dbo.passportversions
  FOR EACH STATEMENT EXECUTE FUNCTION dbo.passportversions_append_only();

-- Geen RLS: op RDS bestaan de publieke Supabase-rollen niet meer; toegang loopt
-- uitsluitend via de applicatierol (zie docs/aws-security-checklist.md).

-- Lease-locks voor achtergrondtaken (bijv. het dagelijkse onderhoud): bij meerdere
-- ECS-taken pakt er precies één de taak op, zonder een databaseverbinding vast te
-- houden. Een verlopen lease (taak gecrasht) kan door een andere taak worden
-- overgenomen.
CREATE TABLE IF NOT EXISTS dbo.joblocks (
  name varchar(100) NOT NULL PRIMARY KEY,
  locked_until timestamptz NOT NULL,
  locked_by varchar(200) NOT NULL
);
