const fs = require("fs");
const path = require("path");
const { getPool, close } = require("../src/config/db");

// Postgres-migraties voor Supabase (supabase/migrations, oplopend op bestandsnaam).
// De oude Azure SQL-migraties in migrations/ zijn historie en draaien hier niet.
const MIGRATIONS_DIR = path.join(__dirname, "..", "supabase", "migrations");

async function runMigrations() {
  const pool = await getPool();

  await pool.query(`
    CREATE SCHEMA IF NOT EXISTS dbo;
    CREATE TABLE IF NOT EXISTS dbo.schemamigrations (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      filename varchar(255) NOT NULL UNIQUE,
      applied_at timestamptz NOT NULL DEFAULT now()
    );
  `);
  const appliedResult = await pool.query("SELECT filename FROM dbo.schemamigrations");
  const applied = new Set(appliedResult.rows.map((row) => row.filename));

  const files = fs
    .readdirSync(MIGRATIONS_DIR)
    .filter((file) => file.endsWith(".sql"))
    .sort();

  for (const file of files) {
    if (applied.has(file)) {
      console.log(`↷ overslaan (al toegepast): ${file}`);
      continue;
    }

    const migrationSql = fs.readFileSync(path.join(MIGRATIONS_DIR, file), "utf8");
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      await client.query(migrationSql);
      await client.query("INSERT INTO dbo.schemamigrations (filename) VALUES ($1)", [file]);
      await client.query("COMMIT");
      console.log(`✅ toegepast: ${file}`);
    } catch (error) {
      await client.query("ROLLBACK");
      throw new Error(`Migratie mislukt (${file}): ${error.message}`);
    } finally {
      client.release();
    }
  }
}

runMigrations()
  .then(async () => {
    console.log("Alle migraties zijn bijgewerkt.");
    await close();
    process.exit(0);
  })
  .catch(async (error) => {
    console.error("❌ Migratie mislukt:");
    console.error(error.message);
    await close();
    process.exit(1);
  });
