-- VeriPasso op Supabase Postgres: volledig schema, gelijk aan de eindstand van de
-- oude Azure SQL-migraties 001–017 (zie migrations/ voor de historie).
--
-- Uitgangspunten:
-- - Alles in schema "dbo": de queries in de code verwijzen al naar dbo.<Tabel>
--   (Postgres vouwt ongequote namen naar kleine letters, dus dbo.Users = dbo.users).
--   Bijkomend voordeel: Supabase's publieke Data API (PostgREST) ontsluit alleen
--   "public" - deze tabellen zijn voor anon/authenticated-sleutels onbereikbaar.
--   RLS staat daarnaast aan (zonder policies) als tweede slot; de app verbindt als
--   tabeleigenaar en heeft daar geen last van.
-- - Azure SQL vergeleek tekst hoofdletterongevoelig; Postgres niet. E-mailadressen
--   zijn daarom uniek op lower(email) en de code zoekt op lower(email).
-- - Idempotent (IF NOT EXISTS), zodat opnieuw draaien veilig is.

CREATE SCHEMA IF NOT EXISTS dbo;

CREATE TABLE IF NOT EXISTS dbo.plans (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  max_users integer NOT NULL DEFAULT 1,
  max_products integer NOT NULL DEFAULT 10,
  feature_flags text NULL,
  partner_assignable boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dbo.companies (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(200) NOT NULL,
  slug varchar(100) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'active',
  plan_id integer NULL REFERENCES dbo.plans(id),
  -- Bedrijfslogo als base64-data-URI (max ~200KB, afgedwongen in de API).
  logo text NULL,
  license_start date NULL,
  license_end date NULL,
  kind varchar(20) NOT NULL DEFAULT 'customer',
  partner_id integer NULL REFERENCES dbo.companies(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_companies_slug UNIQUE (slug),
  CONSTRAINT chk_companies_status CHECK (status IN ('active', 'blocked', 'suspended', 'archived')),
  CONSTRAINT chk_companies_kind CHECK (kind IN ('customer', 'partner')),
  -- Alleen klantbedrijven kunnen een partner hebben.
  CONSTRAINT chk_companies_partner_on_customer CHECK (partner_id IS NULL OR kind = 'customer')
);

CREATE TABLE IF NOT EXISTS dbo.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id integer NULL REFERENCES dbo.companies(id),
  email varchar(256) NOT NULL,
  password_hash varchar(255) NULL,
  first_name varchar(100) NULL,
  last_name varchar(100) NULL,
  role varchar(30) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'active',
  -- Historisch (Entra External ID). Alleen nog gebruikt voor accounts die tijdens de
  -- overgangsfase nog geen lokaal wachtwoord hebben; zie src/config/entra.js.
  entra_object_id varchar(255) NULL,
  entra_subject_id varchar(255) NULL,
  must_change_password boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_users_role CHECK (role IN ('platform_owner', 'partner_admin', 'company_admin', 'company_user')),
  CONSTRAINT chk_users_status CHECK (status IN ('active', 'blocked', 'suspended', 'archived', 'deleted')),
  CONSTRAINT chk_users_has_auth_method
    CHECK (password_hash IS NOT NULL OR entra_subject_id IS NOT NULL OR entra_object_id IS NOT NULL)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email_lower ON dbo.users (lower(email));
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_entra_subject_id ON dbo.users (entra_subject_id) WHERE entra_subject_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_entra_object_id ON dbo.users (entra_object_id) WHERE entra_object_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_users_company_id ON dbo.users (company_id);

CREATE TABLE IF NOT EXISTS dbo.sessions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES dbo.users(id),
  token_hash char(64) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  impersonator_user_id integer NULL REFERENCES dbo.users(id),
  CONSTRAINT uq_sessions_token_hash UNIQUE (token_hash)
);
CREATE INDEX IF NOT EXISTS ix_sessions_user_id ON dbo.sessions (user_id);

CREATE TABLE IF NOT EXISTS dbo.companyadmininvites (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id integer NOT NULL REFERENCES dbo.companies(id),
  email varchar(256) NOT NULL,
  first_name varchar(100) NULL,
  last_name varchar(100) NULL,
  token_hash char(64) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'pending',
  invited_by integer NULL REFERENCES dbo.users(id),
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_companyadmininvites_token_hash UNIQUE (token_hash),
  CONSTRAINT chk_companyadmininvites_status CHECK (status IN ('pending', 'accepted', 'revoked', 'expired'))
);
CREATE INDEX IF NOT EXISTS ix_companyadmininvites_company_id ON dbo.companyadmininvites (company_id);

CREATE TABLE IF NOT EXISTS dbo.products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id integer NOT NULL REFERENCES dbo.companies(id),
  name varchar(200) NOT NULL,
  brand varchar(150) NULL,
  model varchar(150) NULL,
  sku varchar(100) NULL,
  gtin varchar(50) NULL,
  category_id integer NULL,
  category_label varchar(100) NULL,
  description text NULL,
  manufacturer varchar(200) NULL,
  country_of_origin varchar(100) NULL,
  status varchar(20) NOT NULL DEFAULT 'draft',
  -- Permanente QR-sleutel: {QR_BASE_URL}/p/{public_id}. Nooit wijzigen of hergebruiken.
  public_id uuid NULL,
  published_at timestamptz NULL,
  -- JSON-array van korte strings ("In het kort").
  highlights text NULL,
  photo_url varchar(1000) NULL,
  -- Objectnaam in de privé-bucket product-images (geen URL, geen secret).
  photo_blob_name varchar(255) NULL,
  created_by integer NULL REFERENCES dbo.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_products_public_id UNIQUE (public_id),
  CONSTRAINT chk_products_status CHECK (status IN ('draft', 'published', 'archived'))
);
CREATE INDEX IF NOT EXISTS ix_products_company_id ON dbo.products (company_id);

CREATE TABLE IF NOT EXISTS dbo.documents (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id integer NOT NULL REFERENCES dbo.companies(id),
  product_id integer NOT NULL REFERENCES dbo.products(id),
  type varchar(50) NOT NULL,
  title varchar(200) NOT NULL,
  language varchar(10) NULL,
  storage_url varchar(1000) NULL,
  -- Objectnaam in de privé-bucket product-documents.
  blob_name varchar(300) NULL,
  file_size integer NULL,
  mime_type varchar(100) NULL,
  is_public boolean NOT NULL DEFAULT false,
  category varchar(30) NOT NULL DEFAULT 'document',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_documents_category CHECK (category IN ('document', 'manual', 'video', '3d_model')),
  CONSTRAINT chk_documents_has_source CHECK (storage_url IS NOT NULL OR blob_name IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS ix_documents_product_id ON dbo.documents (product_id);
CREATE INDEX IF NOT EXISTS ix_documents_company_id ON dbo.documents (company_id);

CREATE TABLE IF NOT EXISTS dbo.productparts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL REFERENCES dbo.products(id),
  company_id integer NOT NULL REFERENCES dbo.companies(id),
  part_number varchar(100) NOT NULL,
  name varchar(200) NOT NULL,
  description text NULL,
  image_url varchar(1000) NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_productparts_product_id ON dbo.productparts (product_id);

CREATE TABLE IF NOT EXISTS dbo.productsustainability (
  product_id integer NOT NULL PRIMARY KEY REFERENCES dbo.products(id),
  co2_footprint_kg numeric(10, 2) NULL,
  co2_reduction_pct numeric(5, 2) NULL,
  recycled_material_pct numeric(5, 2) NULL,
  -- JSON-array van { material, pct }.
  materials text NULL,
  epd_url varchar(1000) NULL,
  recyclable boolean NULL,
  reach_conform boolean NULL,
  rohs_conform boolean NULL,
  expected_lifespan_years integer NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dbo.productcompliance (
  product_id integer NOT NULL PRIMARY KEY REFERENCES dbo.products(id),
  ce_marked boolean NULL,
  -- JSON-array van strings.
  applicable_regulations text NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dbo.productbatches (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL REFERENCES dbo.products(id),
  company_id integer NOT NULL REFERENCES dbo.companies(id),
  batch_number varchar(100) NOT NULL,
  production_date date NULL,
  quantity integer NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_productbatches_product_id ON dbo.productbatches (product_id);

CREATE TABLE IF NOT EXISTS dbo.scanevents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL REFERENCES dbo.products(id),
  scanned_at timestamptz NOT NULL DEFAULT now(),
  user_agent varchar(500) NULL,
  referrer varchar(1000) NULL
);
CREATE INDEX IF NOT EXISTS ix_scanevents_product_id ON dbo.scanevents (product_id);
CREATE INDEX IF NOT EXISTS ix_scanevents_scanned_at ON dbo.scanevents (scanned_at);

CREATE TABLE IF NOT EXISTS dbo.auditlogs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id integer NULL REFERENCES dbo.companies(id),
  user_id integer NULL REFERENCES dbo.users(id),
  -- Bewust geen FK (zelfde als in Azure SQL): blijft herleidbaar, ook historisch.
  impersonator_user_id integer NULL,
  action varchar(100) NOT NULL,
  entity_type varchar(50) NOT NULL,
  entity_id varchar(50) NULL,
  timestamp timestamptz NOT NULL DEFAULT now(),
  metadata text NULL
);
CREATE INDEX IF NOT EXISTS ix_auditlogs_company_id ON dbo.auditlogs (company_id);
CREATE INDEX IF NOT EXISTS ix_auditlogs_company_timestamp ON dbo.auditlogs (company_id, timestamp DESC) INCLUDE (action, entity_type, user_id);
CREATE INDEX IF NOT EXISTS ix_auditlogs_entity ON dbo.auditlogs (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS ix_auditlogs_user_id ON dbo.auditlogs (user_id);

CREATE TABLE IF NOT EXISTS dbo.systemmetricssnapshots (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  taken_at timestamptz NOT NULL DEFAULT now(),
  database_size_bytes bigint NULL,
  database_max_bytes bigint NULL,
  blob_storage_bytes bigint NULL,
  blob_count integer NULL,
  partner_count integer NOT NULL DEFAULT 0,
  company_count integer NOT NULL DEFAULT 0,
  user_count integer NOT NULL DEFAULT 0,
  active_user_count integer NOT NULL DEFAULT 0,
  product_count integer NOT NULL DEFAULT 0,
  document_count integer NOT NULL DEFAULT 0,
  audit_log_count integer NOT NULL DEFAULT 0,
  scan_event_count integer NOT NULL DEFAULT 0,
  invite_count integer NOT NULL DEFAULT 0,
  -- JSON: per-tabel rijen/bytes en per-bucket opslagverdeling.
  table_stats text NULL,
  blob_stats text NULL
);
CREATE INDEX IF NOT EXISTS ix_systemmetricssnapshots_taken_at ON dbo.systemmetricssnapshots (taken_at);

CREATE TABLE IF NOT EXISTS dbo.systemrequestmetricshourly (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bucket_start timestamptz NOT NULL,
  -- scope: 'api' | 'public' (publieke paspoortpagina's) | 'page' (overige pagina's)
  scope varchar(20) NOT NULL,
  -- route is een patroon ('/api/products/:id'), nooit een concrete URL met id's.
  route varchar(200) NOT NULL,
  method varchar(10) NOT NULL,
  request_count integer NOT NULL,
  error_4xx_count integer NOT NULL DEFAULT 0,
  error_5xx_count integer NOT NULL DEFAULT 0,
  duration_sum_ms bigint NOT NULL DEFAULT 0,
  duration_max_ms integer NOT NULL DEFAULT 0,
  p50_ms integer NULL,
  p95_ms integer NULL,
  p99_ms integer NULL
);
CREATE INDEX IF NOT EXISTS ix_systemrequestmetricshourly_bucket ON dbo.systemrequestmetricshourly (bucket_start);

-- Tweede slot naast het niet-ontsloten schema: RLS aan zonder policies, en geen
-- rechten voor de publieke Supabase-rollen. De app (tabeleigenaar) merkt hier niets van.
DO $$
DECLARE
  t record;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'dbo' LOOP
    EXECUTE format('ALTER TABLE dbo.%I ENABLE ROW LEVEL SECURITY', t.tablename);
  END LOOP;

  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON SCHEMA dbo FROM anon, authenticated;
    REVOKE ALL ON ALL TABLES IN SCHEMA dbo FROM anon, authenticated;
  END IF;
END $$;

-- Privé-buckets voor uploads (alleen op Supabase; een kale lokale Postgres heeft
-- geen storage-schema). Limieten zijn gelijk aan de API-limieten, zodat ook een
-- directe upload via een signed upload-URL ze niet kan omzeilen.
DO $$
BEGIN
  IF to_regclass('storage.buckets') IS NOT NULL THEN
    INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    VALUES
      ('product-images', 'product-images', false, 5242880,
        ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']),
      ('product-documents', 'product-documents', false, 10485760,
        ARRAY['application/pdf', 'image/jpeg', 'image/png', 'image/svg+xml', 'image/webp'])
    ON CONFLICT (id) DO UPDATE
      SET public = false,
          file_size_limit = EXCLUDED.file_size_limit,
          allowed_mime_types = EXCLUDED.allowed_mime_types;
  END IF;
END $$;
